name = "external-auth-rule-eval"
workers_dev = true
compatibility_date = "2024-08-06"
main = "index.js"

[[kv_namespaces]]
binding = "KV"
id = "79b068c685fc4a71b8941a145abf51bf"

[vars]
TEAM_DOMAIN="<update>.cloudflareaccess.com"
DEBUG=false